import React, { useState, useEffect } from 'react';
import { getUserLocation, sendContext, getAlerts } from '../services/api';
import { getHeartbeat, getNoiseLevel, isMicrophoneEnabled } from '../services/deviceSimulator';

function Alerts({ selectedPhobias }) {
  const [alerts, setAlerts] = useState([]);
  const [context, setContext] = useState({});
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchContext = async () => {
      try {
        const loc = await getUserLocation();
        const data = await sendContext({ ...loc, timestamp: new Date().toISOString() });
        setContext({
          location_type: data.context?.location?.type || data.context?.location?.amenity || null,
          locationName: data.context?.location?.address?.city || 'Unknown',
          altitude: data.context?.weather?.elevation || null,
          temperature: data.context?.weather?.temperature_2m || null,
          weather_code: data.context?.weather?.weather_code || null,
          season: getSeason(),
          is_night: isNight(data.context?.sun)
        });
      } catch (e) {
        console.log('Context error:', e.message);
      }
      setLoading(false);
    };
    fetchContext();
  }, []);

  useEffect(() => {
    if (selectedPhobias.length === 0 || loading) return;

    const checkAlerts = async () => {
      const sensorContext = {
        ...context,
        heart_rate: getHeartbeat(),
        noise_level: isMicrophoneEnabled() ? getNoiseLevel() : null
      };

      try {
        const newAlerts = await getAlerts(selectedPhobias, sensorContext, []);
        setAlerts(newAlerts);
      } catch (e) {
        console.log('Alerts error:', e.message);
      }
    };

    checkAlerts();
    const interval = setInterval(checkAlerts, 10000);
    return () => clearInterval(interval);
  }, [selectedPhobias, context, loading]);

  const getSeason = () => {
    const month = new Date().getMonth();
    if (month >= 2 && month <= 4) return 'Spring';
    if (month >= 5 && month <= 7) return 'Summer';
    if (month >= 8 && month <= 10) return 'Fall';
    return 'Winter';
  };

  const isNight = (sun) => {
    if (!sun) return false;
    const now = new Date();
    return now < new Date(sun.sunrise) || now > new Date(sun.sunset);
  };

  return (
    <div className="page-container">
      <h1>Alerts & Notifications</h1>
      <div className="context-display">
        <p>📍 Location: {context.locationName || 'Loading...'}</p>
        <p>🏷️ Type: {context.location_type || 'Unknown'}</p>
        <p>🌸 Season: {context.season}</p>
        <p>🌡️ Temperature: {context.temperature !== null ? `${context.temperature}°C` : 'N/A'}</p>
        <p>⛰️ Altitude: {context.altitude !== null ? `${context.altitude}m` : 'N/A'}</p>
      </div>

      <section className="alerts-section">
        <h2>Active Alerts</h2>
        {loading ? (
          <div className="alert-card info"><p>Loading...</p></div>
        ) : alerts.length === 0 ? (
          <div className="alert-card success">
            <h3>✓ No Active Triggers</h3>
            <p>You're all clear! No phobia triggers detected in your current context.</p>
          </div>
        ) : (
          alerts.map(alert => (
            <div key={alert.id} className={`alert-card ${alert.severity}`}>
              <h3>⚠️ {alert.phobiaName}</h3>
              <p>{alert.message}</p>
              <span className="timestamp">{new Date(alert.createdAt).toLocaleString()}</span>
            </div>
          ))
        )}
      </section>

      <div className="device-info-box">
        <h3>📱 How Alerts Work</h3>
        <p>Alerts are generated by matching your phobias with sensor data (location, weather, heart rate, noise) and group messages.</p>
      </div>
    </div>
  );
}

export default Alerts;
